### ISSUE TITLE
Отзыв по проекту

### ISSUE THREAD

**Issue by RichCake** [dimasmir03/Calc_GO#1]
Привет. Я оцениваю твой проект.

Замечания по коду:

1. Не работает указание порта. Все равно запускается на 8080
2. В ридми в 156 строке у тебя написано `"error": "Expression is not valid"`, а сервер выдает `{"error":"invalid character"}`

Замечания в хорошем смысле:

1. Ошибки сервер выдает со смыслом
2. Тесты есть и они хорошие
3. Все разделено на пакеты
4. И общее впечатление осталось хорошим 👍 

Исправишь два недочета и поставлю 💯

**Comment by dimasmir03** [comment]
Привет. Спасибо за твою оценки моей работы!

Вот мои исправления твоих замечаний::
1)  Исправил, теперь работает указание порта.
2) Исправил выражение в запросе чтобы соответствовал ошибке " invalid
expression  ". А ошибка  "invalid character" приводится в примере ниже

Спасибо, что указал мне на мои недочеты. Я обновил репозиторий, можешь
проверять

пн, 23 дек. 2024 г. в 13:59, RichCake ***@***.***>:

**Comment by RichCake** [comment]
Поставил 💯
